SELECT	TABLE_SCHEMA,
		TABLE_NAME
FROM    INFORMATION_SCHEMA.TABLES
WHERE	(TABLE_TYPE = 'BASE TABLE')
AND		(TABLE_NAME <> 'dtproperties')
AND		(TABLE_NAME NOT LIKE 'sys%')
AND		(TABLE_NAME NOT LIKE 'MS%')
ORDER BY TABLE_NAME