name: Build and Test

on: pull_request

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal --configuration Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: WinQuickCompare
        path: src/WinQuickCompare/bin/Release/net8.0-windows
